### ISSUE TITLE
页面内容怎么修改？

### ISSUE THREAD

**Issue by Rensr0** [HAmacd/xxqg_web#1]
作者您好，我根据此链接[https://github.com/sjkhsl/study_xxqg](url)中的docker运行这一步骤将镜像拷贝到我的docker库中，且能正常运行，请问我该如何更改网页内的内容呢？

**Comment by HAmacd** [comment]
自行查看文件夹内的md文件

**Comment by lei01023** [comment]
> 自行查看文件夹内的md文件

我安装了npm之后，运行npm start时找不到这个web路径，我是直接复制的那个docker配置的代码，并没有手动下载文件，所以找不到web文件夹，请问该如何寻找这个路径呢？

**Comment by HAmacd** [comment]
你的问题和我的代码没有任何关系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月19日(周二) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HAmacd/xxqg_web] 页面内容怎么修改？ (Issue #1)




  
自行查看文件夹内的md文件
  
我安装了npm之后，运行npm start时找不到这个web路径，我是直接复制的那个docker配置的代码，并没有手动下载文件，所以找不到web文件夹，请问该如何寻找这个路径呢？

**Comment by lei01023** [comment]
> 你的问题和我的代码没有任何关系
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年12月19日(周二) 晚上9:05 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [HAmacd/xxqg_web] 页面内容怎么修改？ (Issue #1) 自行查看文件夹内的md文件 我安装了npm之后，运行npm start时找不到这个web路径，我是直接复制的那个docker配置的代码，并没有手动下载文件，所以找不到web文件夹，请问该如何寻找这个路径呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，麻烦您了
